### ISSUE TITLE
Upload de fonte de dados

### ISSUE THREAD

**Issue by rommeldias** [eubr-bigsea/docker-lemonade#16]
Olá. Esta dúvida diz respeito ao cadastro de uma fonte de dados (via Lemonade) através de uma chamada. Atualmente, estou utilizando:

curl -k -X POST 'http://localhost:23456/api/v1/limonero/datasources?api_token=IFot3GApzqyF1hx' -d '{"name": "Fonte 1", "url": "/home/Desktop/arquivo.csv", "storage_id": 1, "format": "CSV"}' -H 'Content-type: application/json'

para cadastrar "arquivo.csv" como uma fonte de dados. O seguinte retorno é exibido:

{"data": {"id": 1, "name": "Fonte 1", "description": null, "enabled": true, "statistics_process_counter": 0, "read_only": true, "privacy_aware": false, "created": "2021-12-21T16:22:17+00:00", "updated": "2021-12-21T16:22:18+00:00", "format": "CSV", "initialization": "NO_INITIALIZED", "initialization_job_id": null, "provenience": null, "estimated_rows": 0, "estimated_size_in_mega_bytes": null, "expiration": null, "user_id": 1, "user_login": "admin@lemonade.org.br", "user_name": "Admin ", "tags": null, "temporary": false, "workflow_id": null, "task_id": null, "attribute_delimiter": null, "record_delimiter": null, "text_delimiter": null, "is_public": false, "treat_as_missing": null, "encoding": null, "is_first_line_header": false, "is_multiline": false, "command": null, "is_lookup": false, "use_in_workflow": false, "attributes": [], "permissions": [], "storage": {"id": 1, "name": "Default (local)", "type": "HDFS", "enabled": true, "client_url": null, "extra_params": null}}}

No entanto, por si só, a chamada não parece ser suficiente para o cadastro da fonte de dados de fato, pois quando me dirijo à plataforma do Lemonade, o nome "Fonte 1" está presente na lista de fontes de dados, porém sem o upload do arquivo efetivamente. Por exemplo, não é possível visualizá-lo (Unsupported protocol), inferir schema ou fazer o download.

Há alguma outra API que deve ser chamada?

Ps.: mesmo que o upload fosse realizado por outro aplicação que não fosse o Lemonade, apenas aquela chamada não é o suficiente então, correto?

Obrigado,
Rommel.

**Comment by waltersf** [comment]
Rommel, no email que lhe enviei, eu menciono isso: 
"O upload do arquivo será feito por qual aplicação? Pelo Lemonade? Se for, tem mais APIs a serem chamadas. Se for pela aplicação de vocês, a url é o caminho completo para o arquivo, dentro do armazenamento. Por exemplo, se o armazenamento 1 é HDFS, url será algo como hdfs://servidor/caminho/arquivo.csv. Se for um sistema de arquivos normal, seria algo como /srv/dados/arquivo.csv. Se vocês forem usar S3, aí tem que implementar o suporte no Lemonade, mas a princípio, o Spark deveria suportar, adicionando as dependências necessárias. O campo url seria algo como s3://bucket/caminho/arquivo.csv. "

Se for por outra aplicação, bastaria ajustar a url.

**Comment by waltersf** [comment]
Sugiro implementar o upload pela aplicação de vocês, porque assim dá para personalizar a forma de envio e o gerenciamento.

**Comment by rommeldias** [comment]
> Sugiro implementar o upload pela aplicação de vocês, porque assim dá para personalizar a forma de envio e o gerenciamento.

Opa, Walter. Minha mensagem anterior foi pouco precisa.

Neste primeiro momento, decidimos deixar a cargo do Lemonade o upload. Você mencionou que outras APIs devem ser chamadas. Você poderia indicar quais são e se há uma ordem específica para as chamadas? O que tentamos fazer foi colocar o arquivo desejado na pasta storage criada pelo Lemonade e fazer somente aquela chamada que você havia colocado no e-mail.

Agradeço mais uma vez o auxílio.

**Comment by waltersf** [comment]
> Neste primeiro momento, decidimos deixar a cargo do Lemonade o upload. Você mencionou que outras APIs devem ser chamadas. Você poderia indicar quais são e se há uma ordem específica para as chamadas? O que tentamos fazer foi colocar o arquivo desejado na pasta storage criada pelo Lemonade e fazer somente aquela chamada que você havia colocado no e-mail.

Colocar o arquivo na pasta não funcionou? 

Sobre usar o Lemonade, acho que pode ficar complicado se o usuário final tiver que interagir com o Lemonade diretamente.  Avaliem isso aí, porque a API de upload foi feita para atender o cliente do Lemonade, ela talvez não atenda o que vocês estão querendo fazer. 

A API é :
DataSourceUploadApi           GET, POST           /datasources/upload

Mas eu uso uma biblioteca que envia pedaços do arquivo de forma que grandes arquivos possam ser enviados.

**Comment by rommeldias** [comment]
> > Neste primeiro momento, decidimos deixar a cargo do Lemonade o upload. Você mencionou que outras APIs devem ser chamadas. Você poderia indicar quais são e se há uma ordem específica para as chamadas? O que tentamos fazer foi colocar o arquivo desejado na pasta storage criada pelo Lemonade e fazer somente aquela chamada que você havia colocado no e-mail.
> 
> Colocar o arquivo na pasta não funcionou?
> 
> Sobre usar o Lemonade, acho que pode ficar complicado se o usuário final tiver que interagir com o Lemonade diretamente. Avaliem isso aí, porque a API de upload foi feita para atender o cliente do Lemonade, ela talvez não atenda o que vocês estão querendo fazer.
> 
> A API é : DataSourceUploadApi GET, POST /datasources/upload
> 
> Mas eu uso uma biblioteca que envia pedaços do arquivo de forma que grandes arquivos possam ser enviados.

Opa, Walter.

Não ficou clara para mim a questão da interação que você citou. O usuário irá apenas carregar uma arquivo de dados (via Lemonade), executar uma trilha e obter um retorno.

Sobre o upload, o que fiz até então foi a chamada

curl -k -X POST 'http://localhost:23456/api/v1/limonero/datasources?api_token=IFot3GApzqyF1hx' -d '{"name": "API Data Storage 3", "url": "/home/Desktop/arquivo.csv", "storage_id": 1, "format": "CSV"}' -H 'Content-type: application/json'

que cadastra "API Data Storage 3" como uma fonte de dados. Porém, aparentemente vazia. Colocar arquivo.csv diretamente em "/srv/lemonade/storage/srv/storage/limonero/data/" não força o upload. Esse foi o primeiro teste que fiz.

Fiz alguns testes com chamadas POST a /datasources/upload e algumas dúvidas surgiram em razão de erros que obtive.

A chamada para todas as APIs precisa de um api_token=IFot3GApzqyF1hx ao final (para um dado token válido)?

Na chamada do upload, os parâmetros obrigatórios são resumableIdentifier, resumableFilename e resumableChunkNumber?

Por fim, como é feita a relação de uma fonte de dados criada e de um upload realizado? Sendo mais claro: a fonte de dados "API Data Storage 3" foi criada inicialmente vazia. Como a API de upload direciona o arquivo carregado para essa fonte de dados? É por meio de algum parâmetro?

**Comment by waltersf** [comment]
> Não ficou clara para mim a questão da interação que você citou. O usuário irá apenas carregar uma arquivo de dados (via Lemonade), executar uma trilha e obter um retorno.

Acho que não é tão simples assim. O usuário vai carregar 2 arquivos, não? Um com a lista de arquivos e outro com as imagens?  Como as imagens serão carregadas? Qual o tamanho delas?


> Sobre o upload, o que fiz até então foi a chamada
> 
> curl -k -X POST 'http://localhost:23456/api/v1/limonero/datasources?api_token=IFot3GApzqyF1hx' -d '{"name": "API Data Storage 3", "url": "/home/Desktop/arquivo.csv", "storage_id": 1, "format": "CSV"}' -H 'Content-type: application/json'

Sim. A fonte de dados tem duas "partes": os metadados (nome, localização, armazenamento, etc) e o dado propriamente dito. Essa API só atualiza os metadados. O valor de "url" ("/home/Desktop/arquivo.csv") deveria ser "url": "file:///home/Desktop/arquivo.csv", e se esse arquivo existe em um disco que é acessível ao Lemonade, já estaria pronto.

> que cadastra "API Data Storage 3" como uma fonte de dados. Porém, aparentemente vazia. Colocar arquivo.csv diretamente em "/srv/lemonade/storage/srv/storage/limonero/data/" não força o upload. Esse foi o primeiro teste que fiz.
A url estava correta, com file:///? No exemplo que você postou, "url": "/home/Desktop/arquivo.csv", não e também não inclui 
/srv/lemonade/storage/srv/storage/limonero/data/. Faz um upload pelo Lemonade de um CSV e faz um SELECT na tabela data_source. Você verá a url. Depois, vá ao diretório /srv/lemonade/storage/srv/storage/limonero/data/ e veja como foi criada a estrutura. 


> Fiz alguns testes com chamadas POST a /datasources/upload e algumas dúvidas surgiram em razão de erros que obtive.
> 
> A chamada para todas as APIs precisa de um api_token=IFot3GApzqyF1hx ao final (para um dado token válido)?
Sim, para autenticação. Do contrário, você teria que usar um token que é da aplicação web do Lemonade, o que é bem mais complicado.

> 
> Na chamada do upload, os parâmetros obrigatórios são resumableIdentifier, resumableFilename e resumableChunkNumber?
Sim. Você tem que considerar que o upload pode ser de um arquivo grande. E esse endpoint da API foi feito para atender a interface. Eu uso a biblioteca https://github.com/23/resumable.js/. Como vocês não usam a interface web do Lemonade, vocês teriam que implementar algo similar na aplicação de vocês.  

> Por fim, como é feita a relação de uma fonte de dados criada e de um upload realizado? Sendo mais claro: a fonte de dados "API Data Storage 3" foi criada inicialmente vazia. Como a API de upload direciona o arquivo carregado para essa fonte de dados? É por meio de algum parâmetro?
O campo url aponta para onde o arquivo está, só isso. Mas tem que ter o protocolo, seja ele file:// ou hdfs://. Se vocês forem usar buckets na Amazon S3, teria mais um tipo, s3:// (isto não é suportado ainda).

**Comment by rommeldias** [comment]
Opa, Walter. Agradeço ao suporte prestado. Deu certo por aqui. Colocamos o arquivo no diretório que o Lemonade cria. Para a chamada, utilizamos:

curl -k -X POST 'http://localhost:23456/api/v1/limonero/datasources?api_token=QHNNuHBQOU2KIwl' -d '{"name": "Fonte 1", "url": "file:/srv/storage/srv/storage/limonero/data/fontes.csv", "storage_id": 1, "attribute_delimiter": ",", "is_first_line_header": 1, "format": "CSV"}' -H 'Content-type: application/json'

Isto é, colocamos na chamada "attribute_delimiter": "," e "is_first_line_header": 1 para a fonte de dados ser efetivamente reconhecida. Sem eles, não dava certo.

Obrigado mais uma vez.
