### ISSUE TITLE
Variável associada à leitura de dados

### ISSUE THREAD

**Issue by rommeldias** [eubr-bigsea/docker-lemonade#18]
Oi, Wálter. Tudo bem?

Felizmente conseguimos efetuar o upload de fontes de dados e as chamadas parametrizadas.

No entanto, a caixa "Ler dados" do Lemonade exige a seleção de uma fonte de dados cadastrada. Haveria uma forma de parametrizar esse campo? Notamos que ele é associado ao inteiro ID da  fonte.

Tentamos criar uma variável e associá-la à fonte na aba "Publicação" da caixa "Ler dados", mas sem sucesso.

Agradecemos o auxílio de sempre.

**Comment by waltersf** [comment]
@rommeldias ,

Testei associar a variável e aqui funcionou, com o código que está no branch master do Juicer. Se você não está usando-o, talvez valha a pena atualizar.

Está fazendo algo semelhante à esta imagem?
![image](https://user-images.githubusercontent.com/170966/149567515-080a0d84-c7e1-4897-aee3-07ce336d9033.png)

Note que a caixa de seleção tem que estar habilitada, senão perde a configuração. 
Um jeito de testar a geração de código é o rodar o código a seguir, com as devidas adaptações (isso irá mostrar o código Python que seria gerado, sem no entanto executar o fluxo):
```
$ PYTHONPATH=. python juicer/jobs/code_gen.py  -c ../juicer.yaml -w 35 --lang pt --vars vars.yaml
```
`-w 35` é o id do fluxo e `--vars vars.yaml` é um arquivo com as variáveis. Basicamente, chave + valor separado por dois-pontos. Por exemplo, o meu tem:

```
$ cat vars.yaml
fonte: 4
```

Aí no código gerado você tem que ver se a fonte de dados foi alterada.
