### ISSUE TITLE
Inicialização do Lemonade

### ISSUE THREAD

**Issue by rommeldias** [eubr-bigsea/docker-lemonade#19]
Boa noite,

Trabalhamos com chamadas a APIs para uso dos recursos do Lemonade (execução de trilha, checagem de status, etc).

Um fato que ocorreu recentemente foi o seguinte: o Lemonade executou um job; após um tempo considerável de máquina ocioso, fizemos uma chamada ao id do job para recuperar o status. O seguinte erro foi dado como retorno:

{'status': 'ERROR', 'message': 'Could not verify your access level for that URL. You have to login with proper credentials provided by Lemonade Thorn'}

Há alguma sugestão do que poderia ser? Ao visitar a plataforma, o status da execução foi 'completed'.

Em paralelo a isso, algumas vezes, ao acessarmos a plataforma pela primeira vez no dia, há um pequeno delay para a inicialização do Lemonade. Seria esse o problema desse status de erro?

Agradeço a atenção.

**Comment by waltersf** [comment]
Essa mensagem de erro é por conta da autenticação. É a mesma chamada, passando o token, que vocês já vinham fazendo? O token de autenticação foi informado? Sobre o delay de inicialização, em geral é o tempo para disparar o processo no sistema operacional e possivelmente a carga dos dados. Depois de carregados os dados, as execuções subsequentes são mais rápidas. O processo fica aberto por até 5 minutos de ociosidade.
